export const INCREMENT = 'INCREMENT'
export const RESET = 'RESET'
export const LOGIN_FAIL = 'LOGIN_FAIL'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'
export const LOGOUT_FAIL = 'LOGOUT_FAIL'

export const SET_USER_INFO = 'SET_USER_INFO'

export const OS_NAME = 'OS_NAME'
export const SET_THEME = 'SET_THEME'
export const WINDOW_RESIZE = 'WINDOW_RESIZE'

export const SHOW_LOGIN_POPUP = 'SHOW_LOGIN_POPUP'
export const HIDE_LOGIN_POPUP = 'HIDE_LOGIN_POPUP'

export const PLAYING_GAME = 'PLAYING_GAME'
export const NO_PLAYING_GAME = 'NO_PLAYING_GAME'
export const TRIGGER_LOGIN = 'TRIGGER_LOGIN'
export const CLEAR_CALLBACK = 'CLEAR_CALLBACK'
export const SET_CALLBACK = 'SET_CALLBACK'

export const SHOW_FOOTER = 'SHOW_FOOTER'

export const GET_LANGUAGLE = 'GET_LANGUAGLE'

export const SET_LOGIN_STATE = 'SET_LOGIN_STATE'
